
# Applied Economics Software II — Week 5  
## Reading and Working with CSV, Excel, and JSON Files in Python
### Prepared by  
**Eren Eskicioğlu**  
[GitHub](https://github.com/MrESKK)


This notebook explains how to read different file types in Python by using **pandas**.  
The examples focus on **CSV**, **Excel**, and **JSON** files, and also show basic data selection, filtering, indexing, and cleaning operations.

The notebook is written in a simple and structured way so that a beginner can follow each step easily.

###Note:
You can access the data files required for this notebook from [link](https://github.com/MrESKK/Applied-Economics-Software-II/tree/main/Data) provided in this repository.


## Importing the Required Library

The main library used in this notebook is **pandas**.  
It is one of the most important Python libraries for reading and analyzing data.

In [1]:

import pandas as pd


## Connecting Google Drive

Since the data files are stored in Google Drive, the first step is to mount Drive in Google Colab.  
After running the following code, Colab will ask for permission to access your Drive.

**Note:** If you are not using Google Colab, you do not need this step.  
You can simply read the files from your local computer by writing the correct file path.

In [7]:

from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Reading CSV Files

A **CSV file** (Comma-Separated Values) is one of the most common file types used in data analysis.  
It stores data in table form, where each row is a record and each column is a variable.


## Loading a CSV File

The following code reads the file `countries_of_the_world.csv` from Google Drive and stores it in a DataFrame called `df`.

**Note:** A DataFrame is a table-like data structure in pandas.

In [8]:

df = pd.read_csv('/content/drive/MyDrive/Data/countries_of_the_world.csv')
df

             Country                               Region
0       Afghanistan         ASIA (EX. NEAR EAST)
1           Albania   EASTERN EUROPE
2           Algeria   NORTHERN AFRICA
3    American Samoa   OCEANIA
4           Andorra   WESTERN EUROPE
..               ...                                  ...
222       West Bank   NEAR EAST
223  Western Sahara   NORTHERN AFRICA
224           Yemen   NEAR EAST
225          Zambia   SUB-SAHARAN AFRICA
226        Zimbabwe   SUB-SAHARAN AFRICA

[227 rows x 2 columns]


## Displaying Specific Countries

The next example selects only some countries from the DataFrame.  
This is useful when we want to focus on a small group of observations.

In [12]:

df[df["Country"].isin(["Afghanistan", "Sweden", "Brazil"])]

Empty DataFrame
Columns: [Country, Region]
Index: []


## Viewing One Column

Sometimes we may want to look at only one variable.  
The following code displays only the `Country` column.

In [10]:

df["Country"]

0         Afghanistan
1             Albania
2             Algeria
3      American Samoa
4             Andorra
            ...
222         West Bank
223    Western Sahara
224             Yemen
225            Zambia
226          Zimbabwe
Name: Country, Length: 227, dtype: object


## Displaying the First Rows

The `head()` function is used to display the first observations in a DataFrame.  
This is a practical way to quickly understand the structure of the data.

In [13]:

df.head(10)

              Country                               Region
0        Afghanistan         ASIA (EX. NEAR EAST)
1            Albania   EASTERN EUROPE
2            Algeria   NORTHERN AFRICA
3     American Samoa   OCEANIA
4            Andorra   WESTERN EUROPE
5             Angola   SUB-SAHARAN AFRICA
6           Anguilla               LATIN AMER. & CARIB
7  Antigua & Barbuda               LATIN AMER. & CARIB
8          Argentina               LATIN AMER. & CARIB
9            Armenia                  C.W. OF IND. STATES


# Reading Excel Files

Excel files are also widely used in economics, business, and social sciences.  
Pandas can read Excel files with the `read_excel()` function.


## Loading an Excel File

The file `world_population.xlsx` is read and stored in a DataFrame called `df_excel`.

In [14]:

df_excel = pd.read_excel('/content/drive/MyDrive/Data/world_population.xlsx')
df_excel

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km¬≤),Density (per km¬≤),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,630587.0,10257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,988702.0,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,188531.0,10164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,2224774.0,0.9831,0
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,1705641.0,2026-01-01 00:00:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81493.0,0.9953,0
230,172,ESH,Western Sahara,El Aai√∫n,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,21654.0,10184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,638232.0,10217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,265976.0,1028,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,417665.0,10204,0.2


## Selecting the Top 10 Countries by Rank

This example selects countries whose rank is less than or equal to 10, and then sorts them by rank.

In [15]:

big_countries = df_excel[df_excel["Rank"] <= 10].sort_values("Rank")
big_countries

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km¬≤),Density (per km¬≤),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,1468933.0,1,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,4310675.0,10068,17.77
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,360935.0,10038,2024-04-01 00:00:00
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,1446529.0,10064,1945-03-01 00:00:00
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,2674018.0,10191,1996-02-01 00:00:00
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,2365759.0,10241,1974-02-01 00:00:00
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,252841.0,10046,2026-07-02 00:00:00
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160035.0,10108,2015-02-01 00:00:00
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,84636.0,0.9973,1981-01-01 00:00:00
131,10,MEX,Mexico,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,649082.0,10063,2026-06-01 00:00:00


## Sorting the Same Countries Alphabetically

The same group of countries can also be sorted by country name instead of rank.

In [16]:

alphabetical_countries = df_excel[df_excel["Rank"] <= 10].sort_values("Country")
alphabetical_countries

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km¬≤),Density (per km¬≤),Growth Rate,World Population Percentage
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160035.0,10108,2015-02-01 00:00:00
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,252841.0,10046,2026-07-02 00:00:00
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,1468933.0,1,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,4310675.0,10068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,1446529.0,10064,1945-03-01 00:00:00
131,10,MEX,Mexico,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,649082.0,10063,2026-06-01 00:00:00
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,2365759.0,10241,1974-02-01 00:00:00
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,2674018.0,10191,1996-02-01 00:00:00
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,84636.0,0.9973,1981-01-01 00:00:00
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,360935.0,10038,2024-04-01 00:00:00


## Filtering Specific Countries by Name

The `isin()` function helps us check whether values belong to a list.  
Here, only Albania, Sweden, and Brazil are selected.

In [17]:

specific_countries = df_excel[df_excel["Country"].isin(["Albania", "Sweden", "Brazil"])]
specific_countries

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km¬≤),Density (per km¬≤),Growth Rate,World Population Percentage
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,988702.0,0.9957,0.04
27,7,BRA,Brazil,Brasilia,South America,215313498.0,213196304.0,205188205.0,196353492.0,175873720.0,150706446.0,122288383.0,96369875.0,8515767.0,252841.0,10046,2026-07-02 00:00:00
200,87,SWE,Sweden,Stockholm,Europe,10549347.0,10368969.0,9849349.0,9381729.0,8871043.0,8548406.0,8311763.0,8027702.0,450295.0,234276.0,10079,0.13


## Filtering Countries by Country Code

In many datasets, countries are represented by short codes.  
The following example selects countries according to the `CCA3` code.

In [18]:

specific_countries_cca3 = df_excel[df_excel["CCA3"].isin(["USA", "GBR", "DEU", "TUR", "CZE"])]
specific_countries_cca3

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km¬≤),Density (per km¬≤),Growth Rate,World Population Percentage
50,88,CZE,Czech Republic,Prague,Europe,10493986.0,10530953.0,10523798.0,10464749.0,10234710.0,10301192.0,10270060.0,9795744.0,78865.0,1330627.0,0.9984,0.13
74,19,DEU,Germany,Berlin,Europe,83369843.0,83328988.0,82073226.0,81325090.0,81551677.0,79370196.0,77786703.0,78294583.0,357114.0,2334544.0,0.9995,2026-05-01 00:00:00
213,18,TUR,Turkey,Ankara,Asia,85341241.0,84135428.0,79646178.0,73195345.0,64113547.0,54324142.0,44089069.0,35540990.0,783562.0,1089145.0,10067,2026-07-01 00:00:00
220,21,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,2779289.0,10034,0.85
221,3,USA,United States,"Washington, D.C.",North America,338289857.0,335942003.0,324607776.0,311182845.0,282398554.0,248083732.0,223140018.0,200328340.0,9372610.0,360935.0,10038,2024-04-01 00:00:00


## Searching for a Word Inside a Column

The `str.contains()` function is useful when we want to find all rows that contain a specific word.  
Below, the rows including the word **Republic** are displayed.

In [19]:

df_excel[df_excel["Country"].str.contains("Republic", na=False)]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km¬≤),Density (per km¬≤),Growth Rate,World Population Percentage
38,117,CAF,Central African Republic,Bangui,Africa,5579144.0,5343020.0,4819333.0,4660067.0,3759170.0,2809221.0,2415276.0,2067356.0,622984.0,89555.0,10224,0.07
50,88,CZE,Czech Republic,Prague,Europe,10493986.0,10530953.0,10523798.0,10464749.0,10234710.0,10301192.0,10270060.0,9795744.0,78865.0,1330627.0,0.9984,0.13
54,84,DOM,Dominican Republic,Santo Domingo,North America,11228821.0,10999664.0,10405832.0,9775755.0,8540791.0,7129004.0,5755800.0,4475871.0,48671.0,2307087.0,2026-01-01 00:00:00,0.14
168,114,COG,Republic of the Congo,Brazzaville,Africa,5970424.0,5702174.0,5064386.0,4437884.0,3134030.0,2385435.0,1829256.0,1396989.0,342000.0,174574.0,10231,0.07


## Selecting Only Certain Columns

Sometimes we only need a few variables from a dataset.  
This example displays only the `Country` and `Capital` columns.

In [20]:

df_excel[["Country", "Capital"]]

               Country           Capital
0          Afghanistan             Kabul
1              Albania            Tirana
2              Algeria           Algiers
3       American Samoa         Pago Pago
4              Andorra  Andorra la Vella
..                 ...               ...
229  Wallis and Futuna          Mata-Utu
230     Western Sahara         El Aai√∫n
231              Yemen             Sanaa
232             Zambia            Lusaka
233           Zimbabwe            Harare

[234 rows x 2 columns]


## Setting a Column as the Index

An index helps us identify rows more clearly.  
In this example, the `Country` column is used as the new index.

In [21]:

df_excel_new_index = df_excel.set_index("Country")
df_excel_new_index

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km¬≤),Density (per km¬≤),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,630587.0,10257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,988702.0,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,188531.0,10164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,2224774.0,0.9831,0
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,1705641.0,2026-01-01 00:00:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81493.0,0.9953,0
Western Sahara,172,ESH,El Aai√∫n,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,21654.0,10184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,638232.0,10217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,265976.0,1028,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,417665.0,10204,0.2


## Filtering Rows by Index Label

After setting `Country` as the index, we can search by row labels more easily.

In [22]:

df_excel_new_index.filter(items=["Zimbabwe"], axis=0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km¬≤),Density (per km¬≤),Growth Rate,World Population Percentage
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,417665.0,10204,0.2


## Filtering Index Labels That Contain a Word

The `filter()` function can also be used with `like=` to find labels containing a certain expression.

In [23]:

df_excel_new_index.filter(like="United", axis=0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km¬≤),Density (per km¬≤),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
United Arab Emirates,97,ARE,Abu Dhabi,Asia,9441129.0,9287289.0,8916899.0,8481771.0,3275333.0,1900151.0,1014048.0,298084.0,83600.0,1129322.0,10081,0.12
United Kingdom,21,GBR,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,2779289.0,10034,0.85
United States,3,USA,"Washington, D.C.",North America,338289857.0,335942003.0,324607776.0,311182845.0,282398554.0,248083732.0,223140018.0,200328340.0,9372610.0,360935.0,10038,2024-04-01 00:00:00
United States Virgin Islands,200,VIR,Charlotte Amalie,North America,99465.0,100442.0,102803.0,106142.0,108185.0,100685.0,96640.0,63446.0,347.0,2866427.0,0.9937,0


## Dropping an Unnecessary Column

Sometimes a dataset contains columns that are not needed for analysis.  
The following code removes the `Area (km¬≤)` column.

In [25]:

df_excel_dropped = df_excel.drop(columns=["Area (km¬≤)"])
df_excel_dropped

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Density (per km¬≤),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,630587.0,10257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,988702.0,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,188531.0,10164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,2224774.0,0.9831,0
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,1705641.0,2026-01-01 00:00:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,81493.0,0.9953,0
230,172,ESH,Western Sahara,El Aai√∫n,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,21654.0,10184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,638232.0,10217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,265976.0,1028,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,417665.0,10204,0.2


## Checking the Shape of the DataFrame

The `shape` command tells us the number of rows and columns in a DataFrame.

In [26]:

df_excel.shape

(234, 17)


## Selecting Rows with a Condition

This example selects the row where the country rank is equal to 1.

In [27]:

df_excel[df_excel["Rank"] == 1]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km¬≤),Density (per km¬≤),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,1468933.0,1,17.88


## Selecting Countries from a Specific Continent

Here, only European countries are shown.

In [28]:

df_excel[df_excel["Continent"] == "Europe"]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km¬≤),Density (per km¬≤),Growth Rate,World Population Percentage
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,988702.00,0.9957,0.04
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,1705641.00,2026-01-01 00:00:00,0
12,99,AUT,Austria,Vienna,Europe,8939617.0,8907777.0,8642421.0,8362829.0,8010428.0,7678729.0,7547561.0,7465301.0,83871.0,1065877.00,1002,0.11
18,96,BLR,Belarus,Minsk,Europe,9534954.0,9633740.0,9700609.0,9731427.0,10256483.0,10428525.0,9817257.0,9170786.0,207600.0,459295.00,0.9955,0.12
19,81,BEL,Belgium,Brussels,Europe,11655930.0,11561717.0,11248303.0,10877947.0,10264343.0,9959560.0,9828986.0,9629376.0,30528.0,3818111.00,10038,0.15
25,137,BIH,Bosnia and Herzegovina,Sarajevo,Europe,3233526.0,3318407.0,3524324.0,3811088.0,4179350.0,4494310.0,4199820.0,3815561.0,51209.0,631437.00,0.9886,0.04
30,108,BGR,Bulgaria,Sofia,Europe,6781953.0,6979175.0,7309253.0,7592273.0,8097691.0,8767778.0,8980606.0,8582950.0,110879.0,611654.00,0.9849,0.09
46,130,HRV,Croatia,Zagreb,Europe,4030358.0,4096868.0,4254815.0,4368682.0,4548434.0,4873707.0,4680144.0,4492638.0,56594.0,712153.00,0.9927,0.05
49,158,CYP,Cyprus,Nicosia,Europe,1251488.0,1237537.0,1187280.0,1129686.0,948237.0,788500.0,679327.0,640804.0,9251.0,1352814.00,10059,0.02
50,88,CZE,Czech Republic,Prague,Europe,10493986.0,10530953.0,10523798.0,10464749.0,10234710.0,10301192.0,10270060.0,9795744.0,78865.0,1330627.00,0.9984,0.13
51,115,DNK,Denmark,Copenhagen,Europe,5882261.0,5825641.0,5677796.0,5550849.0,5340655.0,5144623.0,5125392.0,4922963.0,43094.0,1364984.00,10048,0.07
61,156,EST,Estonia,Tallinn,Europe,1326062.0,1329444.0,1314657.0,1331535.0,1396877.0,1570674.0,1476983.0,1361999.0,45227.0,293201.00,0.998,0.02
65,209,FRO,Faroe Islands,T√≥rshavn,Europe,53090.0,52415.0,48816.0,48410.0,45660.0,47479.0,43054.0,38416.0,1393.0,38112.00,10038,0
67,118,FIN,Finland,Helsinki,Europe,5540745.0,5529468.0,5479461.0,5363271.0,5176209.0,4986545.0,4779418.0,4606621.0,338424.0,163722.00,10009,0.07
68,23,FRA,France,Paris,Europe,64626628.0,64480053.0,63809769.0,62444567.0,58665453.0,56412897.0,53713830.0,50523586.0,551695.0,1171419.00,10015,0.81
74,19,DEU,Germany,Berlin,Europe,83369843.0,83328988.0,82073226.0,81325090.0,81551677.0,79370196.0,77786703.0,78294583.0,357114.0,2334544.00,0.9995,2026-05-01 00:00:00
76,219,GIB,Gibraltar,Gibraltar,Europe,32649.0,32709.0,32520.0,31262.0,27741.0,27317.0,28734.0,26685.0,6.0,5441.50,0.9994,0
77,90,GRC,Greece,Athens,Europe,10384971.0,10512232.0,10806641.0,11033783.0,11038109.0,10302255.0,9307148.0,8544873.0,131990.0,78.68,0.9942,0.13
83,207,GGY,Guernsey,Saint Peter Port,Europe,63301.0,62794.0,61629.0,60782.0,59114.0,57727.0,52860.0,52656.0,78.0,8115513.00,10037,0
90,94,HUN,Hungary,Budapest,Europe,9967308.0,9750573.0,9844246.0,9986825.0,10202055.0,NaN,NaN,10315366.0,93028.0,1071431.00,10265,0.12
91,179,ISL,Iceland,Reykjav√≠k,Europe,372899.0,366669.0,331060.0,318333.0,281462.0,NaN,NaN,204468.0,103000.0,36204.00,10069,0
96,125,IRL,Ireland,Dublin,Europe,5023109.0,4946119.0,4665760.0,4524585.0,3768950.0,3485374.0,3391387.0,2937637.0,70273.0,714799.00,10073,0.06
97,202,IMN,Isle of Man,Douglas,Europe,84519.0,84046.0,83593.0,83828.0,75562.0,68865.0,64022.0,55298.0,572.0,1477605.00,1003,0
99,25,ITA,Italy,Rome,Europe,59037474.0,59500579.0,60232906.0,59822450.0,56966397.0,56756561.0,56329482.0,53324036.0,301336.0,1959191.00,0.9966,0.74
103,195,JEY,Jersey,Saint Helier,Europe,110778.0,108319.0,100561.0,96151.0,86192.0,82874.0,75124.0,68347.0,116.0,9549828.00,10106,0
111,151,LVA,Latvia,Riga,Europe,1850651.0,1897052.0,1991955.0,2101530.0,2392530.0,2689391.0,2572037.0,2397414.0,64559.0,28666.00,0.9876,0.02
116,216,LIE,Liechtenstein,Vaduz,Europe,39327.0,38756.0,37355.0,35926.0,33026.0,28765.0,25003.0,21089.0,160.0,2457937.00,10074,0
117,141,LTU,Lithuania,Vilnius,Europe,2750055.0,2820267.0,2963765.0,3139019.0,3599637.0,3785847.0,3521206.0,3210147.0,65300.0,421142.00,0.9869,0.03
118,168,LUX,Luxembourg,Luxembourg,Europe,647599.0,630399.0,569408.0,507070.0,435628.0,381267.0,363741.0,339342.0,2586.0,250425.00,10129,0.01
125,173,MLT,Malta,Valletta,Europe,533286.0,515357.0,456579.0,418755.0,399212.0,365392.0,333587.0,315414.0,316.0,16876139.00,10124,0.01
133,135,MDA,Moldova,Chisinau,Europe,3272996.0,3084847.0,3277388.0,3678186.0,4251573.0,4480199.0,4103240.0,3711140.0,33846.0,967026.00,10691,0.04
134,217,MCO,Monaco,Monaco,Europe,36469.0,36922.0,36760.0,33178.0,32465.0,30329.0,27076.0,24270.0,2.0,18234.50,0.9941,0
136,169,MNE,Montenegro,Podgorica,Europe,627082.0,629048.0,633966.0,631044.0,633324.0,621442.0,589324.0,530268.0,13812.0,454012.00,0.9988,0.01
144,71,NLD,Netherlands,Amsterdam,Europe,17564014.0,17434557.0,17041107.0,16617116.0,15899135.0,14944548.0,14130387.0,13037686.0,41850.0,4196897.00,10036,0.22
152,150,MKD,North Macedonia,Skopje,Europe,2093599.0,2111072.0,2107962.0,2093828.0,2037936.0,2044174.0,1907023.0,1656783.0,25713.0,814218.00,0.9954,0.03
154,120,NOR,Norway,Oslo,Europe,NaN,5379839.0,NaN,4889741.0,4491202.0,4241636.0,4085776.0,3875546.0,323802.0,167828.00,10058,0.07
164,37,POL,Poland,Warsaw,Europe,39857145.0,38428366.0,38553146.0,38597353.0,38504431.0,38064255.0,35521429.0,32482943.0,312679.0,1274698.00,10404,0.5
165,92,PRT,Portugal,Lisbon,Europe,10270865.0,10298192.0,10365435.0,10588401.0,10300626.0,10007346.0,9785252.0,8683631.0,92090.0,1115307.00,0.9981,0.13
170,64,ROU,Romania,Bucharest,Europe,19659267.0,19442038.0,19906079.0,20335211.0,21919876.0,22836234.0,22125224.0,19922618.0,238391.0,824665.00,10171,0.25
171,9,RUS,Russia,Moscow,Europe,144713314.0,145617329.0,144668389.0,143242599.0,146844839.0,148005704.0,138257420.0,130093010.0,17098242.0,84636.00,0.9973,1981-01-01 00:00:00
180,218,SMR,San Marino,San Marino,Europe,33660.0,34007.0,33570.0,31608.0,NaN,23132.0,21346.0,18169.0,61.0,5518033.00,0.9975,0
184,105,SRB,Serbia,Belgrade,Europe,7221365.0,7358005.0,7519496.0,7653748.0,7935022.0,7987529.0,7777010.0,7193533.0,88361.0,817257.00,0.9897,0.09
189,116,SVK,Slovakia,Bratislava,Europe,5643453.0,5456681.0,5424444.0,5396424.0,5376690.0,5261305.0,4973883.0,4522867.0,49037.0,1150856.00,10359,0.07
190,148,SVN,Slovenia,Ljubljana,Europe,2119844.0,2117641.0,2080862.0,2057286.0,1984339.0,1986024.0,1901570.0,1741286.0,20273.0,1045649.00,10002,0.03
196,30,ESP,Spain,Madrid,Europe,47558630.0,47363807.0,46431342.0,46572772.0,40741651.0,38889889.0,37491666.0,33792617.0,505992.0,939909.00,10015,0.6
200,87,SWE,Sweden,Stockholm,Europe,10549347.0,10368969.0,9849349.0,9381729.0,8871043.0,8548406.0,8311763.0,8027702.0,450295.0,234276.00,10079,0.13
201,101,CHE,Switzerland,Bern,Europe,8740472.0,8638613.0,8281732.0,7822435.0,7182059.0,6711693.0,6319113.0,6181227.0,41284.0,2117157.00,10056,0.11
218,38,UKR,Ukraine,Kiev,Europe,39701739.0,43909666.0,44982564.0,45683020.0,48879755.0,51589817.0,49973920.0,47279086.0,603500.0,657858.00,0.912,0.5
220,21,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,2779289.00,10034,0.85
226,234,VAT,Vatican City,Vatican City,Europe,510.0,520.0,564.0,596.0,651.0,700.0,733.0,752.0,1.0,510.00,0.998,0


## Using `.loc[]` for Row Selection

The `.loc[]` method is used to access rows by label.  
If the default index is numerical, it can also be used to display row ranges.

In [29]:

df_excel.loc[10]

Rank                                     198
CCA3                                     ABW
Country                                Aruba
Capital                           Oranjestad
Continent                      North America
2022 Population                     106445.0
2020 Population                     106585.0
2015 Population                     104257.0
2010 Population                     100341.0
2000 Population                      89101.0
1990 Population                      65712.0
1980 Population                      62267.0
1970 Population                      59106.0
Area (km¬≤)                            180.0
Density (per km¬≤)                 5913611.0
Growth Rate                           0.9991
World Population Percentage                0
Name: 10, dtype: object

In [30]:

df_excel.loc[0:10]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km¬≤),Density (per km¬≤),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,630587.0,10257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,988702.0,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,188531.0,10164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,2224774.0,0.9831,0
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,1705641.0,2026-01-01 00:00:00,0
5,42,AGO,Angola,Luanda,Africa,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,285466.0,10315,0.45
6,224,AIA,Anguilla,The Valley,North America,15857.0,15585.0,14525.0,13172.0,11047.0,8316.0,6560.0,6283.0,91.0,1742527.0,10066,0
7,201,ATG,Antigua and Barbuda,Saint John‚Äôs,North America,93763.0,92664.0,89941.0,85695.0,75055.0,63328.0,64888.0,64516.0,442.0,2121335.0,10058,0
8,33,ARG,Argentina,Buenos Aires,South America,45510318.0,45036032.0,43257065.0,41100123.0,37070774.0,32637657.0,28024803.0,23842803.0,2780400.0,163683.0,10052,0.57
9,140,ARM,Armenia,Yerevan,Asia,2780469.0,2805608.0,2878595.0,2946293.0,3168523.0,3556539.0,3135123.0,2534377.0,29743.0,934831.0,0.9962,0.03
10,198,ABW,Aruba,Oranjestad,North America,106445.0,106585.0,104257.0,100341.0,89101.0,65712.0,62267.0,59106.0,180.0,5913611.0,0.9991,0


## Selecting Countries with Population Below 1 Million

The following code creates a smaller DataFrame that includes countries with a 2022 population below 1,000,000.

In [31]:

df_population_less_than_1m = df_excel[df_excel["2022 Population"] < 1000000]
df_population_less_than_1m

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km¬≤),Density (per km¬≤),Growth Rate,World Population Percentage
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,2224774.0,0.9831,0
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,1705641.0,2026-01-01 00:00:00,0
6,224,AIA,Anguilla,The Valley,North America,15857.0,15585.0,14525.0,13172.0,11047.0,8316.0,6560.0,6283.0,91.0,1742527.0,10066,0
7,201,ATG,Antigua and Barbuda,Saint John‚Äôs,North America,93763.0,92664.0,89941.0,85695.0,75055.0,63328.0,64888.0,64516.0,442.0,2121335.0,10058,0
10,198,ABW,Aruba,Oranjestad,North America,106445.0,106585.0,104257.0,100341.0,89101.0,65712.0,62267.0,59106.0,180.0,5913611.0,0.9991,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,200,VIR,United States Virgin Islands,Charlotte Amalie,North America,99465.0,100442.0,102803.0,106142.0,108185.0,100685.0,96640.0,63446.0,347.0,2866427.0,0.9937,0
225,181,VUT,Vanuatu,Port-Vila,Oceania,326740.0,311685.0,276438.0,245453.0,192074.0,150882.0,118156.0,87019.0,12189.0,268061.0,10238,0
226,234,VAT,Vatican City,Vatican City,Europe,510.0,520.0,564.0,596.0,651.0,700.0,733.0,752.0,1.0,510.0,0.998,0
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81493.0,0.9953,0
230,172,ESH,Western Sahara,El Aai√∫n,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,21654.0,10184,0.01


## Selecting Certain Columns and Certain Rows Together

In this example, only the `Country` and `2022 Population` columns are selected, and only the first 11 rows are displayed.

In [32]:

df_sub2022_pop = df_excel[["Country", "2022 Population"]].loc[0:10]
df_sub2022_pop

                Country  2022 Population
0           Afghanistan       41128771.0
1               Albania        2842321.0
2               Algeria       44903225.0
3        American Samoa          44273.0
4               Andorra          79824.0
5                Angola       35588987.0
6              Anguilla          15857.0
7   Antigua and Barbuda          93763.0
8             Argentina       45510318.0
9               Armenia        2780469.0
10                Aruba         106445.0


# Reading JSON Files

A **JSON** file is a common format used to store structured data.  
It is especially popular in web applications and APIs.


## Loading a JSON File

The following code reads the file `json_sample.json` and stores it in a DataFrame.

In [33]:

df_json = pd.read_json('/content/drive/MyDrive/Data/json_sample.json')
df_json

,12 Strong,A Fantastic Woman (Una Mujer Fantástica),All The Money In The World,Bilal: A New Breed Of Hero,Call Me By Your Name,Darkest Hour,Den Of Thieves,Ferdinand,Fifty Shades Freed,Film Stars Don'T Die In Liverpool,...,The 15:17 To Paris,The Commuter,The Disaster Artist,The Greatest Showman,The Insult (L'Insulte),The Post,The Shape Of Water,"Three Billboards Outside Ebbing, Missouri",Till The End Of The World,Winchester
0,"{'Genre': 'Action', 'Gross': '$453,173', 'IMDB...","{'popcornscore': 83, 'rating': 'R', 'tomatosco...","{'popcornscore': 71, 'rating': 'R', 'tomatosco...","{'popcornscore': 91, 'rating': 'PG13', 'tomato...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': 84, 'rating': 'PG13', 'tomato...","{'Genre': 'Action', 'Gross': '$491,898', 'IMDB...","{'popcornscore': 49, 'rating': 'PG', 'tomatosc...","{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 69, 'rating': 'R', 'tomatosco...",...,"{'Genre': 'Drama', 'Gross': 'unknown', 'IMDB M...","{'popcornscore': 48, 'rating': 'PG13', 'tomato...","{'popcornscore': 89, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$627,248', 'I...","{'popcornscore': 86, 'rating': 'R', 'tomatosco...","{'Genre': 'Biography', 'Gross': '$463,228', 'I...","{'Genre': 'Adventure', 'Gross': '$448,287', 'I...","{'popcornscore': 87, 'rating': 'R', 'tomatosco...","{'popcornscore': -1, 'rating': 'NR', 'tomatosc...","{'Genre': 'Biography', 'Gross': '$696,786', 'I..."


# Basic Data Cleaning Example

In this section, a different Excel file is used to demonstrate some very basic cleaning operations.


## Loading the Customer Call List File

This file is read into a new DataFrame called `dff`.

In [36]:

df_Customer_Call_List = pd.read_excel('/content/drive/MyDrive/Data/Customer_Call_List.xlsx')
df_Customer_Call_List

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True


## Setting the First Name Column as the Index

This makes row-based operations easier when we want to work with customer names.

In [37]:

new_df_Customer_Call_List = df_Customer_Call_List.set_index("First_Name")
new_df_Customer_Call_List

,CustomerID,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
First_Name,,,,,,,
Frodo,1001,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
Abed,1002,Nadir,123/643/9775,93 West Main Street,No,Yes,False
Walter,1003,/White,7066950392,298 Drugs Driveway,N,NaN,True
Dwight,1004,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
Jon,1005,Snow,876|678|3469,123 Dragons Road,Y,No,True
Ron,1006,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
Jeff,1007,Winger,NaN,1209 South Street,No,No,False
Sherlock,1008,Holmes,876|678|3469,98 Clue Drive,N,No,False
Gandalf,1009,NaN,N/a,123 Middle Earth,Yes,NaN,False
Peter,1010,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
Samwise,1011,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
Harry,1012,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
Don,1013,Draper,123-543-2345,2039 Main Street,Yes,N,False
Leslie,1014,Knope,876|678|3469,343 City Parkway,Yes,No,False
Toby,1015,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
Ron,1016,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
Michael,1017,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
Clark,1018,Kent,7066950392,3498 Super Lane,Y,NaN,True
Creed,1019,Braton,N/a,N/a,N/a,Yes,True
Anakin,1020,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
Anakin,1020,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True


## Dropping One Specific Row

If we want to remove the row for `Jon`, we can use the `drop()` function.

**Important note:**  
In the original notebook, there was an incorrect command.  
The correct function is `drop()`, not `set_r()`.

In [38]:

new_df_Customer_Call_Listt = new_df_Customer_Call_List.drop("Jon")
new_df_Customer_Call_Listt

,CustomerID,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
First_Name,,,,,,,
Frodo,1001,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
Abed,1002,Nadir,123/643/9775,93 West Main Street,No,Yes,False
Walter,1003,/White,7066950392,298 Drugs Driveway,N,NaN,True
Dwight,1004,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
Ron,1006,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
Jeff,1007,Winger,NaN,1209 South Street,No,No,False
Sherlock,1008,Holmes,876|678|3469,98 Clue Drive,N,No,False
Gandalf,1009,NaN,N/a,123 Middle Earth,Yes,NaN,False
Peter,1010,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
Samwise,1011,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
Harry,1012,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
Don,1013,Draper,123-543-2345,2039 Main Street,Yes,N,False
Leslie,1014,Knope,876|678|3469,343 City Parkway,Yes,No,False
Toby,1015,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
Ron,1016,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
Michael,1017,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
Clark,1018,Kent,7066950392,3498 Super Lane,Y,NaN,True
Creed,1019,Braton,N/a,N/a,N/a,Yes,True
Anakin,1020,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
Anakin,1020,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True


## Dropping an Unnecessary Column

The following code removes the column named `Not_Useful_Column`.

In [39]:

cleaned_new_df_Customer_Call_List = new_df_Customer_Call_List.drop(columns=["Not_Useful_Column"])
cleaned_new_df_Customer_Call_List

,CustomerID,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
First_Name,,,,,,
Frodo,1001,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
Abed,1002,Nadir,123/643/9775,93 West Main Street,No,Yes
Walter,1003,/White,7066950392,298 Drugs Driveway,N,NaN
Dwight,1004,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
Jon,1005,Snow,876|678|3469,123 Dragons Road,Y,No
Ron,1006,Swanson,304-762-2467,768 City Parkway,Yes,Yes
Jeff,1007,Winger,NaN,1209 South Street,No,No
Sherlock,1008,Holmes,876|678|3469,98 Clue Drive,N,No
Gandalf,1009,NaN,N/a,123 Middle Earth,Yes,NaN
Peter,1010,Parker,123-545-5421,"25th Main Street, New York",Yes,No
Samwise,1011,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
Harry,1012,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
Don,1013,Draper,123-543-2345,2039 Main Street,Yes,N
Leslie,1014,Knope,876|678|3469,343 City Parkway,Yes,No
Toby,1015,Flenderson_,304-762-2467,214 HR Avenue,N,No
Ron,1016,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
Michael,1017,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
Clark,1018,Kent,7066950392,3498 Super Lane,Y,NaN
Creed,1019,Braton,N/a,N/a,N/a,Yes
Anakin,1020,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
Anakin,1020,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N


# Final Note

This notebook introduced the basic use of pandas for:
- reading CSV files,
- reading Excel files,
- reading JSON files,
- selecting rows and columns,
- filtering data,
- changing the index,
- and applying simple cleaning operations.

For GitHub sharing, do not forget to upload the data files together with the notebook.  
Otherwise, another user may open the notebook but will not be able to run the code successfully.